### ISSUE TITLE
Fix: Screenshots not generated in CLI

### ISSUE THREAD

**Issue by nicolevanderhoeven** [flood-io/cli#11] opened 2018-02-20 09:19 UTC
Screenshots work when running a proper flood, but do not work when running through the CLI. They would make it a lot easier to debug while scripting without having to run full-blown tests.

**Comment by ivanvanderbyl** [comment] 2018-05-29 04:54
Duplicate of #8

**Closed by ivanvanderbyl** 2018-05-29 04:54 UTC
Labels: enhancement
